name: matrix demo
on: push
jobs:
  build:
    continue-on-error: true
    strategy:  # this will execute our jon on the basis of matrix
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest, python-latest]
        include:
         - node-version: 18
           operating-system: ubuntu-latest
        exclude:
         - node-version :  12
           operating-system: python-latest

    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version : 14
      - name: Install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
