name: Reusbale workflow
on: 
  workflow_call:
    inputs:
      artifact-name:  
        description: The name of the deployed artifact file
        type: string
        required: false #if the input value is not present still the workflow will run with defalut value
        default: dist
jobs:
  Reusbale:
    runs-on: ubuntu-latest
    steps:
      - name: Get code  
        run: actions/download-artifact@v3
        with:
          name : ${{ inputs.artifact-name }}  # we are taking the input value from dynamic manner
      - name: List file
        run: ls
      - name: Download-Upload
        run: echo "Upload is successfull........"